# Generated by Django 3.0.2 on 2020-01-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('admin_id', models.IntegerField(blank=True, null=True)),
                ('admin_user', models.CharField(max_length=50, null=True)),
                ('chat_title', models.CharField(blank=True, max_length=50)),
                ('chat_username', models.CharField(max_length=50)),
                ('phone', models.IntegerField(null=True)),
                ('date_purchased', models.DateField(auto_now_add=True)),
                ('is_purchased', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saletype', models.CharField(max_length=50, null=True)),
                ('is_wholesale', models.BooleanField(default=False)),
                ('is_retail', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Senf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senf', models.CharField(max_length=50, null=True)),
                ('shoes', models.BooleanField(default=False)),
                ('bags', models.BooleanField(default=False)),
                ('women_clothes', models.BooleanField(default=False)),
                ('men_clothes', models.BooleanField(default=False)),
                ('kids_clothes', models.BooleanField(default=False)),
                ('underwear', models.BooleanField(default=False)),
                ('makeup', models.BooleanField(default=False)),
                ('homestuff', models.BooleanField(default=False)),
                ('electric_home', models.BooleanField(default=False)),
                ('glasses', models.BooleanField(default=False)),
                ('electrical', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download_url.Button')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(max_length=5000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download_url.Channel')),
            ],
        ),
    ]
