# Generated by Django 3.0.2 on 2020-01-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download_url', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channels',
            new_name='Post',
        ),
    ]
