# Generated by Django 3.0.2 on 2020-01-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download_url', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saletype',
            old_name='saletype',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='senf',
            old_name='senf',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='saletype',
            name='is_retail',
        ),
        migrations.RemoveField(
            model_name='saletype',
            name='is_wholesale',
        ),
        migrations.RemoveField(
            model_name='senf',
            name='bags',
        ),
        migrations.RemoveField(
            model_name='senf',
            name='electric_home',
        ),
        migrations.RemoveField(
            model_name='senf',
            name='electrical',
        ),
        migrations.RemoveField(
            model_name='senf',
            name='glasses',
        ),
        migrations.RemoveField(
            model_name='senf',
            name='homestuff',
        ),
        migrations.RemoveField(
            model_name='senf',
            name='kids_clothes',
        ),
        migrations.RemoveField(
            model_name='senf',
            name='makeup',
        ),
        migrations.RemoveField(
            model_name='senf',
            name='men_clothes',
        ),
        migrations.RemoveField(
            model_name='senf',
            name='shoes',
        ),
        migrations.RemoveField(
            model_name='senf',
            name='underwear',
        ),
        migrations.RemoveField(
            model_name='senf',
            name='women_clothes',
        ),
    ]
