# Generated by Django 3.0.2 on 2020-01-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('download_url', '0002_auto_20200108_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(blank=True, null=True)),
                ('admin_id', models.IntegerField(blank=True, null=True)),
                ('ad_user', models.CharField(blank=True, max_length=50, null=True)),
                ('chat_title', models.CharField(max_length=50)),
                ('chat_username', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='ad_user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='chat_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='chat_username',
        ),
        migrations.AddField(
            model_name='post',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='download_url.Channel'),
        ),
    ]
